#!/usr/bin/env bash
# accepts a url and prints information about it's dns settings
domain=$1
declare -a arr=("www" "lb-01" "web-01" "web-02")
if [ $# -eq 1 ]; then
    for subdomain in "${arr[@]}"
    do
	dig "$subdomain"."$domain" | grep -A1 'ANSWER ' | tail -n -1 | awk '{ print "The subdomain '$subdomain' is a "$4 " record and points to " $5}'
    done
else
    dig "$2"."$domain" | grep -A1 'ANSWER ' | tail -n -1 | awk '{ print "The subdomain '$2' is a "$4 " record and points to " $5}'
fi

