#!/usr/bin/env bash
# generates dump and creates archive                                                            
mysqldump -u root -p "$1"  --all-databases > backup.sql
tar -zcvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
