#!/usr/bin/env bash
# displays 10 times, and on the 9th it will enter hi

j=0
while [ $j -le 9 ]
do
    j=$(( j+1 ))
	echo "Holberton School"
    if [ $j == 9 ]
    then
        echo "Hi"
    fi
done
