#!/usr/bin/env bash
# loops from 1 to 10 prints bad luck and good luck

j=1
while [ $j -le 10 ]
do
	if [ $j = 4 ]; then
	   echo "bad luck"
	elif [ $j = 8 ]; then
	     echo "good luck"
	else
		echo "Holberton School"
	fi
	j=$((j + 1))
done
