#!/usr/bin/env bash
# script i used to install nginx on my local web server
# 'Holberton School' to appear when querying nginx at root
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
